platform :ios, '10.0'
use_frameworks!

#source 'git@git.silvrr.com:Asetku/Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'

target 'ZJKeychain_Example' do
  
  pod 'ZJKeychain', :path => '../'

end
